# Generated by Django 4.2.5 on 2023-10-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_phrase', models.CharField(max_length=255)),
            ],
        ),
    ]
