# Generated by Django 4.2.5 on 2023-10-08 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_possibilities_replies_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='possibility_id',
        ),
        migrations.AddField(
            model_name='possibilities',
            name='match_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.matches'),
            preserve_default=False,
        ),
    ]
