# Generated by Django 4.2.5 on 2023-10-08 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_matches_possibility_id_possibilities_match_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='reply_id',
        ),
        migrations.AddField(
            model_name='replies',
            name='match_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.matches'),
            preserve_default=False,
        ),
    ]
